'use strict';
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const http = require('http');
const WebSocket = require('ws');
const webpush = require('web-push');

const app = express();
app.use(cors({origin: process.env.CORS_ORIGIN === '*' ? true : (process.env.CORS_ORIGIN || '').split(',').map(x=>x.trim()).filter(Boolean)}));
app.use(express.json({limit:'1mb'}));
const server = http.createServer(app);
const wss = new WebSocket.Server({noServer:true});
const PORT = Number(process.env.PORT || 10000);
const BASE = 'https://api.dhan.co/v2';
const IDS = {
 NIFTY:{securityId:process.env.NIFTY_SECURITY_ID||'13',exchangeSegment:'IDX_I',instrument:'INDEX'},
 BANKNIFTY:{securityId:process.env.BANKNIFTY_SECURITY_ID||'25',exchangeSegment:'IDX_I',instrument:'INDEX'},
 FINNIFTY:{securityId:process.env.FINNIFTY_SECURITY_ID||'27',exchangeSegment:'IDX_I',instrument:'INDEX'},
 MIDCPNIFTY:{securityId:process.env.MIDCPNIFTY_SECURITY_ID||'442',exchangeSegment:'IDX_I',instrument:'INDEX'},
 SENSEX:{securityId:process.env.SENSEX_SECURITY_ID||'51',exchangeSegment:'IDX_I',instrument:'INDEX'}
};
const cfg = {autoSubscribe:process.env.AUTO_SUBSCRIBE_INDICES!=='false', live:process.env.ENABLE_LIVE_FEED!=='false', maxClients:+(process.env.MAX_CLIENTS||100), maxSubs:+(process.env.MAX_SUBSCRIPTIONS||5000), staleMs:+(process.env.STALE_AFTER_MS||5000), tickStaleMs:+(process.env.TICK_STALE_MS||15000), tickBuffer:+(process.env.TICK_BUFFER_SIZE||10000), maxTicks:+(process.env.MAX_TICKS_PER_INSTRUMENT||3000), maxCandles:+(process.env.MAX_CANDLES_PER_INSTRUMENT||2000), candleMs:+(process.env.CANDLE_TIMEFRAME_MS||60000), historyTtl:+(process.env.HISTORY_CACHE_TTL_MS||30000)};
const ticks = new Map(), candles = new Map(), historyCache = new Map(), subscriptions = new Map(), pushSubs = new Map();
let dhanWs=null, dhanState='DISCONNECTED', lastDhanMessageAt=0, reconnectTimer=null, stopping=false;
let stats={receivedTicks:0,clientsConnected:0,restRequests:0,lastError:null};
const hasCreds=()=>!!(process.env.DHAN_CLIENT_ID&&process.env.DHAN_ACCESS_TOKEN&&process.env.DHAN_CLIENT_ID!=='YOUR_DHAN_CLIENT_ID'&&process.env.DHAN_ACCESS_TOKEN!=='YOUR_CURRENT_DHAN_ACCESS_TOKEN');
function now(){return Date.now()};
function cleanSymbol(s){return String(s||process.env.DEFAULT_INDEX||'NIFTY').toUpperCase().replace(/[^A-Z0-9_-]/g,'')}
function instrumentFor(symbol){const s=cleanSymbol(symbol);if(IDS[s])return {...IDS[s],symbol:s}; if(/^\d+$/.test(s))return {symbol:s,securityId:s,exchangeSegment:'NSE_FNO',instrument:'OPTIDX'};throw new Error(`Unknown symbol '${s}'. Use a configured index or pass a securityId with exchangeSegment/instrument.`)}
function mapTimeframe(tf){const m=String(tf||'1m').match(/^(1|3|5|15|25|60)m?$/);if(!m)throw new Error('Unsupported timeframe. Supported: 1m, 3m (built from 1m), 5m, 15m, 25m, 60m.');return Number(m[1])}
function normCandle(c){return {time:c.time??c.timestamp,open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:+(c.volume||0),openInterest:c.openInterest??null,source:c.source||'DHAN_HISTORY'}}
function makeKey(seg,id){return `${seg}:${String(id)}`}
function rememberTick(t){const key=makeKey(t.exchangeSegment,t.securityId);const prev=ticks.get(key)||{};const merged={...prev,...t,updatedAt:now(),source:'DHAN_WEBSOCKET'};ticks.set(key,merged);stats.receivedTicks++;
 if(merged.ltp>0){const ms=Number(merged.timestamp||now());const start=Math.floor(ms/cfg.candleMs)*cfg.candleMs;let arr=candles.get(key)||[];let c=arr[arr.length-1];if(!c||c.time!==start){c={time:start,open:merged.ltp,high:merged.ltp,low:merged.ltp,close:merged.ltp,volume:merged.lastTradedQty||0,source:'LIVE_AGGREGATED'};arr.push(c)}else{c.high=Math.max(c.high,merged.ltp);c.low=Math.min(c.low,merged.ltp);c.close=merged.ltp;c.volume=(c.volume||0)+(merged.lastTradedQty||0)}if(arr.length>cfg.maxCandles)arr=arr.slice(-cfg.maxCandles);candles.set(key,arr)}
 broadcast({type:'tick',data:merged});}
function broadcast(msg){const raw=JSON.stringify(msg);for(const ws of wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const sub=ws._subscriptions;if(!sub||sub.size===0||msg.type==='status'||sub.has('*')||sub.has(msg.data?.symbol)||sub.has(makeKey(msg.data?.exchangeSegment,msg.data?.securityId)))ws.send(raw)}}
function parsePacket(buf){try{const b=Buffer.from(buf);if(b.length<8)return null;const code=b.readUInt8(0),len=b.readInt16LE(1),segCode=b.readUInt8(3),sid=b.readInt32LE(4);const seg=({0:'IDX_I',1:'NSE_EQ',2:'NSE_FNO',3:'NSE_CURRENCY',4:'BSE_EQ',5:'MCX_COMM',7:'BSE_CURRENCY',8:'BSE_FNO'})[segCode]||`SEG_${segCode}`;const key=makeKey(seg,sid);const t={securityId:String(sid),exchangeSegment:seg,packetCode:code,packetLength:len};
 if(code===2||code===1){if(b.length>=17){t.ltp=b.readFloatLE(8);t.timestamp=b.readInt32LE(12)*1000;}}
 else if(code===4){if(b.length>=51){Object.assign(t,{ltp:b.readFloatLE(8),lastTradedQty:b.readInt16LE(12),timestamp:b.readInt32LE(14)*1000,averagePrice:b.readFloatLE(18),volume:b.readInt32LE(22),sellQuantity:b.readInt32LE(26),buyQuantity:b.readInt32LE(30),open:b.readFloatLE(34),previousClose:b.readFloatLE(38),high:b.readFloatLE(42),low:b.readFloatLE(46)});}}
 else if(code===5){if(b.length>=13)t.oi=b.readInt32LE(8)}
 else if(code===6){if(b.length>=17){t.previousClose=b.readFloatLE(8);t.previousOi=b.readInt32LE(12)}}
 else if(code===8){if(b.length>=163){Object.assign(t,{ltp:b.readFloatLE(8),lastTradedQty:b.readInt16LE(12),timestamp:b.readInt32LE(14)*1000,averagePrice:b.readFloatLE(18),volume:b.readInt32LE(22),sellQuantity:b.readInt32LE(26),buyQuantity:b.readInt32LE(30),oi:b.readInt32LE(34),highestOi:b.readInt32LE(38),lowestOi:b.readInt32LE(42),open:b.readFloatLE(46),previousClose:b.readFloatLE(50),high:b.readFloatLE(54),low:b.readFloatLE(58),depth:[]});for(let i=0;i<5;i++){let o=63+i*20;t.depth.push({bidQty:b.readInt32LE(o),askQty:b.readInt32LE(o+4),bidOrders:b.readInt16LE(o+8),askOrders:b.readInt16LE(o+10),bidPrice:b.readFloatLE(o+12),askPrice:b.readFloatLE(o+16)})}}}
 else if(code===50){stats.lastError=`Dhan feed disconnect code ${b.length>=10?b.readInt16LE(8):'unknown'}`;return {disconnect:true,code:50,reason:stats.lastError}}
 if(t.ltp!==undefined||t.oi!==undefined||t.previousClose!==undefined){t.symbol=Object.keys(IDS).find(s=>IDS[s].securityId===String(sid))||null;const old=ticks.get(key)||{};const merged={...old,...t,updatedAt:now(),source:'DHAN_WEBSOCKET'};ticks.set(key,merged);if(merged.ltp>0)rememberTick(merged);else broadcast({type:'tick',data:merged});return merged}return null;
 }catch(e){stats.lastError='Binary packet parse: '+e.message;return null}}
function sendSubscribe(ws,items,mode=21){for(let i=0;i<items.length;i+=100){const chunk=items.slice(i,i+100);ws.send(JSON.stringify({RequestCode:mode,InstrumentCount:chunk.length,InstrumentList:chunk.map(x=>({ExchangeSegment:x.exchangeSegment,SecurityId:String(x.securityId)}))}))}}
function connectDhan(){if(stopping||!cfg.live||!hasCreds())return;clearTimeout(reconnectTimer);dhanState='CONNECTING';broadcast({type:'status',data:status()});const url=`wss://api-feed.dhan.co?version=2&token=${encodeURIComponent(process.env.DHAN_ACCESS_TOKEN)}&clientId=${encodeURIComponent(process.env.DHAN_CLIENT_ID)}&authType=2`;try{dhanWs=new WebSocket(url);dhanWs.on('open',()=>{dhanState='CONNECTED';lastDhanMessageAt=now();stats.lastError=null;const base=Object.values(IDS).map(x=>({securityId:x.securityId,exchangeSegment:x.exchangeSegment,symbol:x.symbol}));if(cfg.autoSubscribe)sendSubscribe(dhanWs,base,21);const all=new Map();for(const set of subscriptions.values())for(const item of set)all.set(makeKey(item.exchangeSegment,item.securityId),item);if(all.size)sendSubscribe(dhanWs,[...all.values()],21);broadcast({type:'status',data:status()})});dhanWs.on('message',(data,isBinary)=>{lastDhanMessageAt=now();if(isBinary){const packet=parsePacket(data);if(packet?.disconnect){dhanState='DISCONNECTED';broadcast({type:'status',data:status()})}}else{try{broadcast({type:'broker-message',data:JSON.parse(data.toString())})}catch{}}});dhanWs.on('error',e=>{stats.lastError=e.message;dhanState='ERROR';broadcast({type:'status',data:status()})});dhanWs.on('close',()=>{dhanState='DISCONNECTED';broadcast({type:'status',data:status()});if(!stopping)reconnectTimer=setTimeout(connectDhan,5000)})}catch(e){stats.lastError=e.message;dhanState='ERROR';reconnectTimer=setTimeout(connectDhan,8000)}}
function status(){return {service:'UNIVERSAL_DHAN_MARKET_DATA_ENGINE',version:'1.0.0',dhanConfigured:hasCreds(),dhanState,liveFeedEnabled:cfg.live,lastDhanMessageAt:lastDhanMessageAt||null,feedAgeMs:lastDhanMessageAt?now()-lastDhanMessageAt:null,stale:!lastDhanMessageAt||now()-lastDhanMessageAt>cfg.staleMs,clients:wss.clients.size,subscriptions:[...subscriptions.values()].reduce((n,s)=>n+s.size,0),ticksCached:ticks.size,candleSeriesCached:candles.size,pushEnabled:process.env.PUSH_ENABLED!=='false'&&!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY),lastError:stats.lastError}}
async function dhanPost(path,payload){if(!hasCreds())throw Object.assign(new Error('Dhan credentials missing. Set DHAN_CLIENT_ID and DHAN_ACCESS_TOKEN in the service environment.'),{status:503});stats.restRequests++;const res=await fetch(BASE+path,{method:'POST',headers:{'access-token':process.env.DHAN_ACCESS_TOKEN,'client-id':process.env.DHAN_CLIENT_ID,'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));if(!res.ok)throw Object.assign(new Error(body.errorMessage||body.message||`Dhan HTTP ${res.status}`),{status:res.status,details:body});return body}
function indexTick(symbol){const ins=instrumentFor(symbol);const t=ticks.get(makeKey(ins.exchangeSegment,ins.securityId));return t?{...t,symbol:ins.symbol,ageMs:now()-t.updatedAt,stale:now()-t.updatedAt>cfg.tickStaleMs}:null}
function candlesFromResponse(data){const opens=data.open||[],highs=data.high||[],lows=data.low||[],closes=data.close||[],volumes=data.volume||[],times=data.timestamp||[],ois=data.open_interest||[];return closes.map((close,i)=>({time:Number(times[i]||0)*1000,open:+opens[i],high:+highs[i],low:+lows[i],close:+close,volume:+(volumes[i]||0),openInterest:ois[i]??null,source:'DHAN_HISTORY'})).filter(c=>Number.isFinite(c.close)&&c.time>0)}
async function getCandles(symbol,tf,limit){const ins=instrumentFor(symbol);const minutes=mapTimeframe(tf);const key=`${ins.exchangeSegment}:${ins.securityId}:${minutes}`;const cached=historyCache.get(key);if(cached&&now()-cached.at<cfg.historyTtl){let all=[...cached.data];const live=candles.get(makeKey(ins.exchangeSegment,ins.securityId))||[];if(minutes===1)all=mergeCandles(all,live);return all.slice(-limit)}const to=new Date();const from=new Date(to.getTime()-Math.min(90,Math.max(3,Math.ceil(limit*minutes/375)+2))*86400000);const payload={securityId:String(ins.securityId),exchangeSegment:ins.exchangeSegment,instrument:ins.instrument,interval:String([1,5,15,25,60].includes(minutes)?minutes:1),oi:false,fromDate:fmtDhanDate(from),toDate:fmtDhanDate(to)};const raw=await dhanPost('/charts/intraday',payload);let arr=candlesFromResponse(raw);if(minutes===3)arr=aggregateCandles(arr,3);else if(minutes!==1&&!([5,15,25,60].includes(minutes)))throw new Error('Timeframe not supported');if(minutes===1)arr=mergeCandles(arr,candles.get(makeKey(ins.exchangeSegment,ins.securityId))||[]);arr=arr.slice(-Math.max(1,Math.min(2000,limit)));historyCache.set(key,{at:now(),data:arr});return arr}
function fmtDhanDate(d){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`}
function mergeCandles(a,b){const m=new Map(a.map(c=>[Number(c.time),c]));for(const c of b)m.set(Number(c.time),c);return [...m.values()].sort((x,y)=>x.time-y.time)}
function aggregateCandles(arr,n){const map=new Map();for(const c of arr){const t=Math.floor(c.time/(n*60000))*n*60000;const old=map.get(t);if(!old)map.set(t,{...c,time:t});else{old.high=Math.max(old.high,c.high);old.low=Math.min(old.low,c.low);old.close=c.close;old.volume=(old.volume||0)+(c.volume||0)}}return [...map.values()].sort((a,b)=>a.time-b.time)}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'universal-dhan-market-data-engine',time:new Date().toISOString()}));
app.get('/api/status',(req,res)=>res.json(status()));
app.get('/api/state',(req,res)=>res.json({status:status(),indices:Object.keys(IDS).map(s=>({symbol:s,quote:indexTick(s)}))}));
app.get('/api/config',(req,res)=>res.json({defaultIndex:process.env.DEFAULT_INDEX||'NIFTY',indices:Object.keys(IDS),supportedTimeframes:['1m','3m','5m','15m','25m','60m'],websocketPath:'/ws',dataContract:'universal-market-data-v1'}));
app.get('/api/notifications/vapid-public-key',(req,res)=>{if(!process.env.VAPID_PUBLIC_KEY)return res.status(503).json({error:'VAPID not configured'});res.json({publicKey:process.env.VAPID_PUBLIC_KEY})});
app.get('/api/spot',async(req,res)=>{try{const symbol=cleanSymbol(req.query.symbol);let tick=indexTick(symbol);if(tick)return res.json({symbol,price:tick.ltp,ltp:tick.ltp,previousClose:tick.previousClose??null,change:tick.previousClose?tick.ltp-tick.previousClose:null,changePercent:tick.previousClose?(tick.ltp-tick.previousClose)/tick.previousClose*100:null,timestamp:tick.timestamp,source:tick.source,stale:tick.stale,ageMs:tick.ageMs,marketState:'UNKNOWN'});const ins=instrumentFor(symbol);const raw=await dhanPost('/marketfeed/ohlc',{[ins.exchangeSegment]:[Number(ins.securityId)]});const item=raw?.data?.[ins.exchangeSegment]?.[String(ins.securityId)];if(!item)return res.status(502).json({error:'Dhan did not return quote for symbol',symbol,raw});const price=Number(item.last_price),prev=Number(item.ohlc?.close);res.json({symbol,price,ltp:price,previousClose:Number.isFinite(prev)?prev:null,change:Number.isFinite(prev)?price-prev:null,changePercent:prev?((price-prev)/prev*100):null,source:'DHAN_REST_SNAPSHOT',stale:false,marketState:'UNKNOWN',asOf:new Date().toISOString()})}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
app.get('/api/ticks',(req,res)=>{const symbol=req.query.symbol?cleanSymbol(req.query.symbol):null;let data=[...ticks.values()];if(symbol)data=data.filter(t=>t.symbol===symbol||String(t.securityId)===symbol);res.json({data:data.map(t=>({...t,ageMs:now()-t.updatedAt,stale:now()-t.updatedAt>cfg.tickStaleMs})),count:data.length,status:status()})});
app.get('/api/candles',async(req,res)=>{try{const symbol=cleanSymbol(req.query.symbol||process.env.DEFAULT_INDEX||'NIFTY');const timeframe=String(req.query.timeframe||'1m');const limit=Math.min(2000,Math.max(1,Number(req.query.limit||250)));const data=await getCandles(symbol,timeframe,limit);res.json({symbol,timeframe,candles:data,count:data.length,source:data.some(c=>c.source==='LIVE_AGGREGATED')?'DHAN_HISTORY+LIVE':'DHAN_HISTORY',status:status()})}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
app.get('/api/quote',async(req,res)=>{try{const ins=instrumentFor(req.query.symbol||process.env.DEFAULT_INDEX);const raw=await dhanPost('/marketfeed/quote',{[ins.exchangeSegment]:[Number(ins.securityId)]});res.json({symbol:ins.symbol||ins.securityId,data:raw.data?.[ins.exchangeSegment]?.[String(ins.securityId)]||null,source:'DHAN_REST_SNAPSHOT',asOf:new Date().toISOString()})}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
app.post('/api/subscribe',(req,res)=>{const clientId=String(req.body.clientId||'default');const list=Array.isArray(req.body.instruments)?req.body.instruments:[];if(list.length>cfg.maxSubs)return res.status(413).json({error:'Subscription limit exceeded',limit:cfg.maxSubs});const normalized=[];try{for(const x of list){const ins=x.symbol&&!x.securityId?instrumentFor(x.symbol):{symbol:x.symbol||null,securityId:String(x.securityId),exchangeSegment:String(x.exchangeSegment||'NSE_FNO'),instrument:x.instrument||'OPTIDX'};normalized.push(ins)}}catch(e){return res.status(400).json({error:e.message})}subscriptions.set(clientId,new Set(normalized));if(dhanWs?.readyState===WebSocket.OPEN&&normalized.length)sendSubscribe(dhanWs,normalized,21);res.json({ok:true,clientId,subscribed:normalized.length})});
undefined
const optionChainCache=new Map();
async function getExpiryList(symbol){const ins=instrumentFor(symbol);const key=ins.symbol||ins.securityId;const cached=optionChainCache.get('exp:'+key);if(cached&&now()-cached.at<60000)return cached.data;const raw=await dhanPost('/optionchain/expirylist',{UnderlyingScrip:Number(ins.securityId),UnderlyingSeg:ins.exchangeSegment});const data=Array.isArray(raw.data)?raw.data:[];optionChainCache.set('exp:'+key,{at:now(),data});return data}
app.get('/api/option-chain/expiries',async(req,res)=>{try{const symbol=cleanSymbol(req.query.symbol||process.env.DEFAULT_INDEX);const expiries=await getExpiryList(symbol);res.json({symbol,expiries,source:'DHAN_OPTION_CHAIN'})}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
async function fetchOptionChain(symbol,expiry){const ins=instrumentFor(symbol);let ex=expiry;if(!ex){const xs=await getExpiryList(symbol);ex=xs[0]}if(!ex)throw Object.assign(new Error('No active expiry returned by Dhan'),{status:404});const key='oc:'+symbol+':'+ex;const cached=optionChainCache.get(key);if(cached&&now()-cached.at<3200)return {...cached.data,cached:true};const raw=await dhanPost('/optionchain',{UnderlyingScrip:Number(ins.securityId),UnderlyingSeg:ins.exchangeSegment,Expiry:ex});const src=raw.data||{};const rows=Object.entries(src.oc||{}).map(([strike,v])=>({strike:Number(strike),ce:v.ce?normalizeOption(v.ce):null,pe:v.pe?normalizeOption(v.pe):null})).sort((a,b)=>a.strike-b.strike);const out={symbol,expiry:ex,spot:Number(src.last_price)||null,rows,count:rows.length,source:'DHAN_OPTION_CHAIN',asOf:new Date().toISOString()};optionChainCache.set(key,{at:now(),data:out});return out}
function normalizeOption(o){return {securityId:o.security_id??null,ltp:Number(o.last_price)||0,previousClose:Number(o.previous_close_price)||0,oi:Number(o.oi)||0,previousOi:Number(o.previous_oi)||0,changeOi:(Number(o.oi)||0)-(Number(o.previous_oi)||0),volume:Number(o.volume)||0,previousVolume:Number(o.previous_volume)||0,iv:o.implied_volatility==null?null:Number(o.implied_volatility),delta:o.greeks?.delta??null,gamma:o.greeks?.gamma??null,theta:o.greeks?.theta??null,vega:o.greeks?.vega??null,bid:Number(o.top_bid_price)||0,bidQty:Number(o.top_bid_quantity)||0,ask:Number(o.top_ask_price)||0,askQty:Number(o.top_ask_quantity)||0,averagePrice:Number(o.average_price)||0}}
app.get('/api/option-chain',async(req,res)=>{try{const symbol=cleanSymbol(req.query.symbol||process.env.DEFAULT_INDEX);res.json(await fetchOptionChain(symbol,String(req.query.expiry||'')))}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
app.post('/api/option-chain',async(req,res)=>{try{const symbol=cleanSymbol(req.body?.symbol||process.env.DEFAULT_INDEX);res.json(await fetchOptionChain(symbol,String(req.body?.expiry||'')))}catch(e){res.status(e.status||502).json({error:e.message,details:e.details})}});
app.post('/api/push/subscribe',(req,res)=>{try{const s=req.body?.subscription;if(!s?.endpoint||!s?.keys?.p256dh||!s?.keys?.auth)return res.status(400).json({error:'Invalid Web Push subscription'});pushSubs.set(s.endpoint,{subscription:s,clientId:String(req.body.clientId||'default'),createdAt:now()});res.json({ok:true,subscriptions:pushSubs.size})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/push/test',async(req,res)=>{if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY)return res.status(503).json({error:'VAPID keys are not configured'});try{webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:admin@example.com',process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const payload=JSON.stringify({title:req.body?.title||'Trading alert test',body:req.body?.body||'Universal backend push is working.',tag:'universal-test'});const results=await Promise.allSettled([...pushSubs.values()].map(x=>webpush.sendNotification(x.subscription,payload)));res.json({ok:true,subscriptions:pushSubs.size,delivered:results.filter(x=>x.status==='fulfilled').length,failed:results.filter(x=>x.status==='rejected').length})}catch(e){res.status(500).json({error:e.message})}});
server.on('upgrade',(req,socket,head)=>{if(req.url.split('?')[0]!=='/ws'){socket.destroy();return}if(wss.clients.size>=cfg.maxClients){socket.write('HTTP/1.1 503 Service Unavailable\r\n\r\n');socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});
wss.on('connection',(ws)=>{ws._subscriptions=new Set();ws.send(JSON.stringify({type:'hello',data:{contract:'universal-market-data-v1',status:status(),supportedStreams:['ticks','spot','candles','depth','oi']}}));ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='subscribe'){const syms=Array.isArray(m.symbols)?m.symbols.map(cleanSymbol):[];const streams=Array.isArray(m.streams)?m.streams:['ticks'];if(syms.includes('*'))ws._subscriptions.add('*');for(const s of syms){ws._subscriptions.add(s);try{const ins=instrumentFor(s);if(dhanWs?.readyState===WebSocket.OPEN)sendSubscribe(dhanWs,[ins],streams.includes('depth')?21:streams.includes('quote')?17:15)}catch{}}ws.send(JSON.stringify({type:'subscribed',data:{symbols:syms,streams,timeframe:m.timeframe||'1m'}}))}else if(m.type==='ping')ws.send(JSON.stringify({type:'pong',time:now()}));else if(m.type==='unsubscribe'){for(const s of m.symbols||[])ws._subscriptions.delete(cleanSymbol(s));ws.send(JSON.stringify({type:'unsubscribed',data:{symbols:m.symbols||[]}}))}}catch(e){ws.send(JSON.stringify({type:'error',error:e.message}))}});ws.on('close',()=>{});});
setInterval(()=>{broadcast({type:'status',data:status()});for(const ws of wss.clients)if(ws.readyState===WebSocket.OPEN)ws.ping()},10000).unref();
if(cfg.live&&hasCreds())connectDhan();else{dhanState='NOT_CONFIGURED';console.warn('Dhan feed not started: configure DHAN_CLIENT_ID and DHAN_ACCESS_TOKEN in environment.');}
server.listen(PORT,process.env.HOST||'0.0.0.0',()=>console.log(`Universal Dhan Market Data Engine listening on ${PORT}`));
process.on('SIGTERM',()=>{stopping=true;clearTimeout(reconnectTimer);try{dhanWs?.close()}catch{}server.close(()=>process.exit(0))});
